<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.bundle.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.bundle.js.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.bundle.min.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.bundle.min.js.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.esm.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.esm.js.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.esm.min.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.esm.min.js.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.js.map" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.min.js" />
    <Content Remove="C:\Users\umpg0020097\.nuget\packages\bootstrap\5.2.3\contentFiles\any\any\wwwroot\js\bootstrap.min.js.map" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\fonts\font-awesome\fontawesome-webfontba72.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-bold-webfont.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-bolditalic-webfont.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-italic-webfont.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-light-webfont.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-lightitalic-webfont.svg" />
    <None Include="wwwroot\css\fonts\opensans\opensans-regular-webfont.svg" />
    <None Include="wwwroot\css\fonts\pacifico\pacifico-webfont.svg" />
    <None Include="wwwroot\js\banzhow.js" />
    <None Include="wwwroot\js\bootstrap.js" />
    <None Include="wwwroot\js\jquery-1.10.2.js" />
    <None Include="wwwroot\js\plugins.js" />
    <None Include="wwwroot\js\switcher\switcher.js" />
    <None Include="wwwroot\vendors\bootstrap\bootstrap.bundle.min.js" />
    <None Include="wwwroot\vendors\contact.js" />
    <None Include="wwwroot\vendors\fontawesome\bootstrap.bundle.min.js" />
    <None Include="wwwroot\vendors\fontawesome\webfonts\fa-brands-400.woff2" />
    <None Include="wwwroot\vendors\fontawesome\webfonts\fa-regular-400.woff2" />
    <None Include="wwwroot\vendors\fontawesome\webfonts\fa-solid-900.woff2" />
    <None Include="wwwroot\vendors\img\blog\.DS_Store" />
    <None Include="wwwroot\vendors\img\gallery\.DS_Store" />
    <None Include="wwwroot\vendors\img\Thumbs.db" />
    <None Include="wwwroot\vendors\jquery.ajaxchimp.min.js" />
    <None Include="wwwroot\vendors\jquery.form.js" />
    <None Include="wwwroot\vendors\jquery.validate.min.js" />
    <None Include="wwwroot\vendors\jquery\jquery-3.2.1.min.js" />
    <None Include="wwwroot\vendors\js\main.js" />
    <None Include="wwwroot\vendors\linericon\.DS_Store" />
    <None Include="wwwroot\vendors\linericon\fonts\Linearicons-Free.svg" />
    <None Include="wwwroot\vendors\linericon\fonts\Linearicons-Free.woff2" />
    <None Include="wwwroot\vendors\mail-script.js" />
    <None Include="wwwroot\vendors\nice-select\jquery.nice-select.min.js" />
    <None Include="wwwroot\vendors\nouislider\nouislider.min.js" />
    <None Include="wwwroot\vendors\owl-carousel\owl.carousel.min.js" />
    <None Include="wwwroot\vendors\scss\main.scss" />
    <None Include="wwwroot\vendors\scss\style.scss" />
    <None Include="wwwroot\vendors\scss\theme\_blog.scss" />
    <None Include="wwwroot\vendors\scss\theme\_btn.scss" />
    <None Include="wwwroot\vendors\scss\theme\_cart.scss" />
    <None Include="wwwroot\vendors\scss\theme\_category.scss" />
    <None Include="wwwroot\vendors\scss\theme\_checkout.scss" />
    <None Include="wwwroot\vendors\scss\theme\_confirmation.scss" />
    <None Include="wwwroot\vendors\scss\theme\_contact.scss" />
    <None Include="wwwroot\vendors\scss\theme\_footer.scss" />
    <None Include="wwwroot\vendors\scss\theme\_header.scss" />
    <None Include="wwwroot\vendors\scss\theme\_home.scss" />
    <None Include="wwwroot\vendors\scss\theme\_instagram.scss" />
    <None Include="wwwroot\vendors\scss\theme\_login.scss" />
    <None Include="wwwroot\vendors\scss\theme\_mixins.scss" />
    <None Include="wwwroot\vendors\scss\theme\_register.scss" />
    <None Include="wwwroot\vendors\scss\theme\_reset.scss" />
    <None Include="wwwroot\vendors\scss\theme\_responsive.scss" />
    <None Include="wwwroot\vendors\scss\theme\_section-intro.scss" />
    <None Include="wwwroot\vendors\scss\theme\_single-product.scss" />
    <None Include="wwwroot\vendors\scss\theme\_tracking.scss" />
    <None Include="wwwroot\vendors\scss\theme\_variables.scss" />
    <None Include="wwwroot\vendors\skrollr.min.js" />
    <None Include="wwwroot\vendors\themify-icons\fonts\themify.svg" />
    <None Include="wwwroot\vendors\themify-icons\ie7\ie7.js" />
    <None Include="wwwroot\vendors\themify-icons\SVG\agenda.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\alarm-clock.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\alert.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\align-center.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\align-justify.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\align-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\align-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\anchor.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\android.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-double-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-double-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-double-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-double-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\angle-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\announcement.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\apple.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\archive.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-circle-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-circle-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-circle-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-circle-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-top-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-top-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrow.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrows-corner.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrows-horizontal.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\arrows-vertical.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\back-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\back-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bag.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bar-chart-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bar-chart.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\basketball.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bell.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\blackboard.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bolt-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bolt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\book.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bookmark-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\bookmark.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\briefcase.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\brush-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\brush.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\calendar.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\camera.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\car.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\check-box.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\check.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\clip.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\clipboard.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\close.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\cloud-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\cloud-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\cloud.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\comment-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\comment.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\comments-smiley.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\comments.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-backward.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-eject.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-forward.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-pause.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-play.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-record.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-shuffle.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-skip-backward.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-skip-forward.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\control-stop.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\credit-card.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\crown.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\css3.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\cup.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\cut.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\dashboard.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\desktop.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\direction-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\direction.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\download.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\dribbble.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\dropbox-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\dropbox.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\drupal.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\email.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\envelope.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\eraser.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\exchange-vertical.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\export.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\eye.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\face-sad.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\face-smile.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\facebook.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\file.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\files.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\filter.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\flag-alt-2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\flag-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\flag.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\flickr-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\flickr.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\folder.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\fullscreen.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\gallery.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\game.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\gift.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\github.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\google.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-drag.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-open.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-point-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-point-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-point-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-point-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hand-stop.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\harddrive.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\harddrives.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\headphone-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\headphone.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\heart-broken.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\heart.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\help-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\help.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\home.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\html5.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\hummer.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\id-badge.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\image.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\import.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\infinite.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\info-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\info.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ink-pen.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\instagram.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\Italic.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\joomla.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\jsfiddle.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\key.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layers-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layers.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-accordion-list.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-accordion-merged.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-accordion-separated.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column2-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column3-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column3.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column4-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-column4.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-cta-btn-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-cta-btn-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-cta-center.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-cta-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-cta-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid2-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid2-thumb.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid3-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid3.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid4-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-grid4.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-line-solid.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-list-large-image.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-list-post.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-list-thumb-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-list-thumb.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-center-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-center.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-left-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-overlay-alt-2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-overlay-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-overlay.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-right-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-media-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-menu-full.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-menu-separated.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-menu-v.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-menu.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-placeholder.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-sidebar-2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-sidebar-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-sidebar-none.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-sidebar-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-slider-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-slider.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-tab-min.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-tab-v.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-tab-window.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-tab.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-width-default-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-width-default.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout-width-full.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\layout.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\light-bulb.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\line-dashed.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\line-dotted.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\line-double.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\link.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\linkedin.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\linux.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\list-ol.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\list.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\location-arrow.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\location-pin.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\lock.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\loop.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\magnet.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\map-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\map.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\marker-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\marker.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\medall-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\medall.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\menu-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\menu.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\microphone-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\microphone.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\microsoft-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\microsoft.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\minus.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\mobile.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\money.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\more-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\more.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\mouse-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\mouse.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\music-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\music.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\na.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\new-window.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\notepad.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\package.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\paint-bucket.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\paint-roller.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\palette.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\panel.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\paragraph.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pencil-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pencil-alt2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pencil.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pie-chart.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pin-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pin.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pin2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pinterest-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pinterest.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\plug.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\plus.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\power-off.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\printer.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\pulse.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\quote-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\quote-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\receipt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\reddit.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\reload.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\rocket.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\rss-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\rss.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ruler-alt-2.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ruler-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ruler-pencil.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ruler.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\save-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\save.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\search.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\server.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\settings.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\share-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\share.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\sharethis-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\sharethis.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shield.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shift-left-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shift-left.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shift-right-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shift-right.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shine.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shopping-cart-full.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shopping-cart.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\shortcode.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\signal.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\skype.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\slice.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\smallcap.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\soundcloud.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\split-h.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\split-v-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\split-v.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\spray.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\stack-overflow.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\stamp.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\star.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\stats-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\stats-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\support.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\tablet.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\tag.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\target.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\text.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\themify-favicon-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\themify-favicon.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\themify-logo.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\thought.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\thumb-down.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\thumb-up.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\ticket.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\time.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\timer.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\trash.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\trello.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\truck.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\tumblr-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\tumblr.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\twitter-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\twitter.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\underline.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\unlink.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\unlock.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\upload.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\uppercase.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\user.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\vector.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\video-camera.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\video-clapper.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\view-grid.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\view-list-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\view-list.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\vimeo-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\vimeo.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\volume.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\wallet.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\wand.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\wheelchair.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\widget-alt.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\widget.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\widgetized.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\window.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\wordpress.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\world.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\write.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\yahoo.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\youtube.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\zip.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\zoom-in.svg" />
    <None Include="wwwroot\vendors\themify-icons\SVG\zoom-out.svg" />
    <None Include="wwwroot\wowbook\fonts\BebasNeue-webfont.svg" />
    <None Include="wwwroot\wowbook\js\dd_belatedpng.js" />
    <None Include="wwwroot\wowbook\js\jquery-1.9.1.min.js" />
    <None Include="wwwroot\wowbook\js\jquery.js" />
    <None Include="wwwroot\wowbook\js\modernizr-1.6.min.js" />
    <None Include="wwwroot\wowbook\js\plugins.js" />
    <None Include="wwwroot\wowbook\js\script.js" />
    <None Include="wwwroot\wowbook\LICENSE" />
    <None Include="wwwroot\wowbook\README.md" />
    <None Include="wwwroot\wowbook\sound\page-flip.mp3" />
    <None Include="wwwroot\wowbook\sound\page-flip.ogg" />
    <None Include="wwwroot\wowbook\wow_book.js" />
    <None Include="wwwroot\wowbook\wow_book.min.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.2.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.6" />
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Cbddo.eYazisma">
      <HintPath>..\..\HerkesYazarOlsun\HerkesYazarOlsun.Model\bin\Debug\net7.0\HerkesYazarOlsun.Model.dll</HintPath>
    </Reference>
   <!-- C:\Users\umpg0020097\Desktop\HerkesYazarOlsun\HerkesYazarOlsun.Model\bin\Debug\net7.0\HerkesYazarOlsun.Model.dll -->
  </ItemGroup>

</Project>
