name: CI

on:
  push:
    branches:
      - main
      - test
      - development
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # --------------------
      # Checkout
      # --------------------
      - name: Checkout source
        uses: actions/checkout@v4

      # --------------------
      # .NET
      # --------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      # --------------------
      # Kubernetes config
      # --------------------
      - name: Setup kubeconfig
        if: github.ref_name == 'test' || github.ref_name == 'main'
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      # --------------------
      # Deploy TEST
      # --------------------
      - name: Deploy to TEST
        if: github.ref_name == 'test'
        run: |
          echo "🚀 Deploying to TEST"
          kubectl apply -f k8s/tst.yml

      # --------------------
      # Deploy PROD
      # --------------------
      - name: Deploy to PROD
        if: github.ref_name == 'main'
        run: |
          echo "🚀 Deploying to PROD"
          kubectl apply -f k8s/prod.yml
